// Copyright 2026 Autometiq
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"context"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Autometiq/safeslice/internal/catalog"
	"github.com/Autometiq/safeslice/internal/config"
	"github.com/Autometiq/safeslice/internal/mask"
	"github.com/Autometiq/safeslice/internal/ui"
)

func initCmd() *cobra.Command {
	var (
		from  string
		out   string
		force bool
		root  string
	)
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Generate a safeslice.yaml from your schema, with PII columns detected",
		Long: `init reads your schema and writes a starter configuration with every
likely personal-data column already classified.

Columns the heuristics could not judge are written with a REVIEW comment. Read
them before trusting the output: no name-based heuristic can know that col_7
holds a passport number.`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			ctx := cmd.Context()
			dsn, err := sourceDSN(from)
			if err != nil {
				return err
			}
			if _, err := os.Stat(out); err == nil && !force {
				return fmt.Errorf("%s already exists; pass --force to overwrite it", out)
			}
			conn, err := connectSource(ctx, dsn)
			if err != nil {
				return err
			}
			defer conn.Close(context.Background())

			schemas := flagSchemas
			if len(schemas) == 0 {
				schemas = []string{"public"}
			}
			cat, err := catalog.Load(ctx, conn, schemas)
			if err != nil {
				return err
			}
			if len(cat.Tables) == 0 {
				return fmt.Errorf("no tables found in schemas %s", strings.Join(schemas, ", "))
			}
			body, detected, review := generate(cat, schemas, root)
			if err := os.WriteFile(out, []byte(body), 0o600); err != nil {
				return fmt.Errorf("writing %s: %w", out, err)
			}

			ui.Success("wrote %s", out)
			ui.Mask("%d columns classified automatically", detected)
			if len(review) > 0 {
				// Marked `keep` so the config works immediately, but surfaced
				// loudly: a column nobody read is the one that leaks.
				ui.Warn("%d columns need review (written as `keep`):", len(review))
				for _, c := range review {
					ui.Detail("%s", c)
				}
			}
			if !flagQuiet {
				if len(review) > 0 {
					ui.NextStep("$EDITOR %s", out)
				} else {
					ui.NextStep("safeslice plan")
				}
				ui.Footer()
			}
			return nil
		},
	}
	f := cmd.Flags()
	f.StringVar(&from, "from", "", "source connection string (or SAFESLICE_SOURCE / DATABASE_URL)")
	f.StringVarP(&out, "out", "o", config.DefaultPath, "file to write")
	f.StringVar(&root, "table", "", "root table (default: the most referenced table)")
	f.BoolVar(&force, "force", false, "overwrite an existing file")
	return cmd
}

// generate renders the config by hand rather than through a YAML marshaller,
// because the comments are the point: they are what turns generated output into
// something a human actually reviews.
func generate(cat *catalog.Catalog, schemas []string, root string) (body string, detected int, review []string) {
	if root == "" {
		root = guessRoot(cat)
	}
	cl := mask.Classifier{}

	var b strings.Builder
	b.WriteString("# safeslice configuration\n")
	b.WriteString("# Generated by `safeslice init`. Commit this file: it is what gives\n")
	b.WriteString("# every teammate and every CI job the same masking rules.\n")
	b.WriteString("version: 1\n\nsource:\n  schemas: [" + strings.Join(schemas, ", ") + "]\n\n")
	b.WriteString("slice:\n")
	b.WriteString("  root: " + root + "\n")
	b.WriteString("  # where: \"id = 4821\"   # slice around one specific row\n")
	b.WriteString("  limit: 1000\n  child_depth: 1\n\n")
	b.WriteString("mask:\n")
	b.WriteString("  # Sharing this seed across the team makes everyone's snapshots agree\n")
	b.WriteString("  # on what a given customer was renamed to.\n")
	b.WriteString("  seed: " + root + "-seed\n")
	b.WriteString("  strict: true\n  rules:\n")

	type entry struct {
		key, rule, note string
	}
	var auto, needsReview []entry

	for _, ref := range cat.Refs() {
		t, ok := cat.Table(ref)
		if !ok || t.Partition {
			continue // partitions inherit their parent's columns
		}
		keys := cat.KeyColumns(ref)
		for _, col := range t.Columns {
			// Key columns are never masked, so they never need a rule.
			if keys[col.Name] || !col.Insertable() {
				continue
			}
			key := ref.Name + "." + col.Name
			if r := cl.Rule(ref, col.Name); r != mask.Keep {
				auto = append(auto, entry{key, string(r), ""})
				continue
			}
			for _, c := range cl.Unclassified(t, keys) {
				if c == col.Name {
					needsReview = append(needsReview, entry{key, "keep", "REVIEW: does this hold personal data?"})
					break
				}
			}
		}
	}
	sort.Slice(auto, func(i, j int) bool { return auto[i].key < auto[j].key })
	sort.Slice(needsReview, func(i, j int) bool { return needsReview[i].key < needsReview[j].key })

	if len(auto) > 0 {
		b.WriteString("\n    # Detected from column names.\n")
		for _, e := range auto {
			b.WriteString(fmt.Sprintf("    %s: %s\n", e.key, e.rule))
		}
	}
	if len(needsReview) > 0 {
		b.WriteString("\n    # Free-text columns safeslice could not judge. They are set to `keep`\n")
		b.WriteString("    # so this config runs, but each one is a decision you still owe.\n")
		b.WriteString("    # Change to `redact` to drop the value, or `secret` to replace it.\n")
		for _, e := range needsReview {
			b.WriteString(fmt.Sprintf("    %s: %s   # %s\n", e.key, e.rule, e.note))
			review = append(review, e.key)
		}
	}
	if len(auto) == 0 && len(needsReview) == 0 {
		b.WriteString("    {}\n")
	}

	b.WriteString("\n# Relationships PostgreSQL does not enforce. Rails polymorphic\n")
	b.WriteString("# associations and Django generic relations have no foreign key, so\n")
	b.WriteString("# safeslice cannot see them without being told.\n")
	b.WriteString("# virtual_keys:\n")
	b.WriteString("#   - table: comments\n#     columns: [commentable_id]\n")
	b.WriteString("#     references: {table: posts, columns: [id]}\n")
	b.WriteString("#     when: \"commentable_type = 'Post'\"\n")

	return b.String(), len(auto), review
}

// guessRoot picks the table most other tables point at. That is almost always
// the one a developer wants to slice around -- users, accounts, customers.
func guessRoot(cat *catalog.Catalog) string {
	preferred := map[string]bool{"users": true, "user": true, "accounts": true,
		"account": true, "customers": true, "customer": true, "organizations": true}
	incoming := map[string]int{}
	for _, fk := range cat.FKs {
		incoming[fk.RefTable.Name]++
	}
	best, bestScore := "", -1
	for _, ref := range cat.Refs() {
		if t, ok := cat.Table(ref); ok && t.Partition {
			continue
		}
		score := incoming[ref.Name]
		if preferred[strings.ToLower(ref.Name)] {
			score += 100
		}
		if score > bestScore {
			best, bestScore = ref.Name, score
		}
	}
	return best
}
