// Copyright 2026 Autometiq
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package catalog introspects a PostgreSQL database into the model the rest of
// safeslice plans against: tables, columns, keys, foreign keys and sequences.
//
// Everything here is read-only. The queries deliberately read pg_catalog rather
// than information_schema, because information_schema hides identity columns,
// generated columns and partition parentage — all of which decide whether a
// restore succeeds.
package catalog

import (
	"context"
	"fmt"
	"sort"

	"github.com/jackc/pgx/v5"
)

// Querier is the slice of pgx used here, so tests can substitute a fake.
type Querier interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
}

// Ref is a schema-qualified relation name.
type Ref struct {
	Schema string
	Name   string
}

func (r Ref) String() string { return r.Schema + "." + r.Name }

// Identity/Generated markers as reported by pg_attribute.
const (
	IdentityAlways    = "a" // GENERATED ALWAYS AS IDENTITY - rejects plain INSERT
	IdentityByDefault = "d" // GENERATED BY DEFAULT AS IDENTITY - accepts INSERT
	GeneratedStored   = "s" // GENERATED ALWAYS AS (expr) STORED - cannot be inserted
)

type Column struct {
	Name      string
	Type      string // format_type output, e.g. "character varying(64)"
	TypeOID   uint32
	Num       int
	NotNull   bool
	Identity  string // "", IdentityAlways, IdentityByDefault
	Generated string // "", GeneratedStored
	MaxLen    int    // char/varchar length limit, -1 when unbounded
}

// Insertable reports whether the column may appear in an INSERT column list.
// Stored generated columns may not: Postgres rejects the statement outright.
func (c Column) Insertable() bool { return c.Generated != GeneratedStored }

type Sequence struct {
	Ref    Ref
	Table  Ref
	Column string
}

type Table struct {
	Ref         Ref
	Columns     []Column
	PK          []string
	Uniques     [][]string // unique constraints and unique indexes, PK excluded
	Checks      []string   // pg_get_constraintdef text
	Sequences   []Sequence
	EstRows     int64
	Partitioned bool // declarative partition parent; never holds rows itself
	Partition   bool // a partition; reads should target Parent instead
	Parent      Ref
}

func (t *Table) Column(name string) (Column, bool) {
	for _, c := range t.Columns {
		if c.Name == name {
			return c, true
		}
	}
	return Column{}, false
}

// KeyColumns returns every column participating in the primary key or in any
// foreign key on either side. Masking must never rewrite these.
func (c *Catalog) KeyColumns(ref Ref) map[string]bool {
	out := map[string]bool{}
	if t, ok := c.Tables[ref.String()]; ok {
		for _, col := range t.PK {
			out[col] = true
		}
	}
	for _, fk := range c.FKs {
		if fk.Table == ref {
			for _, col := range fk.Columns {
				out[col] = true
			}
		}
		if fk.RefTable == ref {
			for _, col := range fk.RefColumns {
				out[col] = true
			}
		}
	}
	return out
}

type FK struct {
	Name       string
	Table      Ref
	Columns    []string
	RefTable   Ref
	RefColumns []string

	// Deferrable reports whether SET CONSTRAINTS can postpone this check to
	// COMMIT. Non-deferrable keys in a cycle cannot be loaded in one pass, so
	// the loader has to break the cycle a different way.
	Deferrable bool

	// Virtual marks a relationship declared in config rather than enforced by
	// the database — Rails polymorphic associations and Django generic
	// relations have no pg_constraint row, so the graph cannot see them.
	Virtual bool
	// When is an optional SQL predicate scoping a virtual key, e.g.
	// "commentable_type = 'Post'".
	When string
}

type Catalog struct {
	Tables map[string]*Table // keyed by Ref.String()
	FKs    []FK
}

func (c *Catalog) Table(ref Ref) (*Table, bool) {
	t, ok := c.Tables[ref.String()]
	return t, ok
}

// Refs returns every table name in deterministic order.
func (c *Catalog) Refs() []Ref {
	out := make([]Ref, 0, len(c.Tables))
	for _, t := range c.Tables {
		out = append(out, t.Ref)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].String() < out[j].String() })
	return out
}

// Load reads the full catalog for the given schemas.
func Load(ctx context.Context, q Querier, schemas []string) (*Catalog, error) {
	if len(schemas) == 0 {
		schemas = []string{"public"}
	}
	c := &Catalog{Tables: map[string]*Table{}}
	for _, step := range []struct {
		name string
		fn   func(context.Context, Querier, []string, *Catalog) error
	}{
		{"tables", loadTables},
		{"columns", loadColumns},
		{"constraints", loadConstraints},
		{"unique indexes", loadUniqueIndexes},
		{"foreign keys", loadFKs},
		{"sequences", loadSequences},
	} {
		if err := step.fn(ctx, q, schemas, c); err != nil {
			return nil, fmt.Errorf("catalog: loading %s: %w", step.name, err)
		}
	}
	return c, nil
}

const tablesSQL = `
SELECT n.nspname::text, c.relname::text, c.relkind::text, c.relispartition,
       COALESCE(pn.nspname, '')::text, COALESCE(pc.relname, '')::text,
       c.reltuples::float8
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_inherits i ON i.inhrelid = c.oid
LEFT JOIN pg_class pc ON pc.oid = i.inhparent
LEFT JOIN pg_namespace pn ON pn.oid = pc.relnamespace
WHERE c.relkind IN ('r', 'p') AND n.nspname = ANY($1)`

func loadTables(ctx context.Context, q Querier, schemas []string, c *Catalog) error {
	rows, err := q.Query(ctx, tablesSQL, schemas)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var t Table
		var kind, parentSchema, parentName string
		var est float64
		if err := rows.Scan(&t.Ref.Schema, &t.Ref.Name, &kind, &t.Partition,
			&parentSchema, &parentName, &est); err != nil {
			return err
		}
		t.Partitioned = kind == "p"
		if t.Partition {
			t.Parent = Ref{parentSchema, parentName}
		}
		if est > 0 {
			t.EstRows = int64(est)
		}
		c.Tables[t.Ref.String()] = &t
	}
	return rows.Err()
}

const columnsSQL = `
SELECT n.nspname::text, c.relname::text, a.attname::text,
       format_type(a.atttypid, a.atttypmod), a.atttypid::oid, a.attnum::int,
       a.attnotnull, a.attidentity::text, a.attgenerated::text,
       CASE WHEN a.atttypid IN (1042, 1043) AND a.atttypmod > 4
            THEN a.atttypmod - 4 ELSE -1 END::int
FROM pg_attribute a
JOIN pg_class c ON c.oid = a.attrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('r', 'p') AND a.attnum > 0 AND NOT a.attisdropped
  AND n.nspname = ANY($1)
ORDER BY n.nspname, c.relname, a.attnum`

func loadColumns(ctx context.Context, q Querier, schemas []string, c *Catalog) error {
	rows, err := q.Query(ctx, columnsSQL, schemas)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var ref Ref
		var col Column
		if err := rows.Scan(&ref.Schema, &ref.Name, &col.Name, &col.Type, &col.TypeOID,
			&col.Num, &col.NotNull, &col.Identity, &col.Generated, &col.MaxLen); err != nil {
			return err
		}
		if t, ok := c.Tables[ref.String()]; ok {
			t.Columns = append(t.Columns, col)
		}
	}
	return rows.Err()
}

const constraintsSQL = `
SELECT n.nspname::text, c.relname::text, con.contype::text,
       (SELECT array_agg(a.attname::text ORDER BY u.ord)
          FROM unnest(con.conkey) WITH ORDINALITY AS u(attnum, ord)
          JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = u.attnum),
       pg_get_constraintdef(con.oid)
FROM pg_constraint con
JOIN pg_class c ON c.oid = con.conrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE con.contype IN ('p', 'u', 'c') AND n.nspname = ANY($1)`

func loadConstraints(ctx context.Context, q Querier, schemas []string, c *Catalog) error {
	rows, err := q.Query(ctx, constraintsSQL, schemas)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var ref Ref
		var kind, def string
		var cols []string
		if err := rows.Scan(&ref.Schema, &ref.Name, &kind, &cols, &def); err != nil {
			return err
		}
		t, ok := c.Tables[ref.String()]
		if !ok {
			continue
		}
		switch kind {
		case "p":
			t.PK = cols
		case "u":
			t.Uniques = append(t.Uniques, cols)
		case "c":
			t.Checks = append(t.Checks, def)
		}
	}
	return rows.Err()
}

// Unique indexes without a backing constraint still enforce uniqueness, so
// masking has to treat them the same way. Partial and expression indexes are
// excluded: their columns are not straightforwardly maskable.
const uniqueIndexSQL = `
SELECT n.nspname::text, c.relname::text,
       array_agg(a.attname::text ORDER BY k.ord)
FROM pg_index i
JOIN pg_class c ON c.oid = i.indrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN unnest(i.indkey) WITH ORDINALITY AS k(attnum, ord) ON TRUE
JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = k.attnum
WHERE i.indisunique AND NOT i.indisprimary
  AND i.indpred IS NULL AND NOT (0 = ANY(i.indkey))
  AND n.nspname = ANY($1)
GROUP BY n.nspname, c.relname, i.indexrelid`

func loadUniqueIndexes(ctx context.Context, q Querier, schemas []string, c *Catalog) error {
	rows, err := q.Query(ctx, uniqueIndexSQL, schemas)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var ref Ref
		var cols []string
		if err := rows.Scan(&ref.Schema, &ref.Name, &cols); err != nil {
			return err
		}
		t, ok := c.Tables[ref.String()]
		if !ok || sameCols(t.PK, cols) || containsCols(t.Uniques, cols) {
			continue
		}
		t.Uniques = append(t.Uniques, cols)
	}
	return rows.Err()
}

// conkey/confkey order is significant and array_agg does not preserve it
// without WITH ORDINALITY — a composite key would otherwise pair the wrong
// columns and silently produce a wrong slice.
const fkSQL = `
SELECT con.conname::text, n.nspname::text, c.relname::text,
       (SELECT array_agg(a.attname::text ORDER BY u.ord)
          FROM unnest(con.conkey) WITH ORDINALITY AS u(attnum, ord)
          JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = u.attnum),
       rn.nspname::text, rc.relname::text,
       (SELECT array_agg(a.attname::text ORDER BY u.ord)
          FROM unnest(con.confkey) WITH ORDINALITY AS u(attnum, ord)
          JOIN pg_attribute a ON a.attrelid = con.confrelid AND a.attnum = u.attnum),
       con.condeferrable
FROM pg_constraint con
JOIN pg_class c ON c.oid = con.conrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_class rc ON rc.oid = con.confrelid
JOIN pg_namespace rn ON rn.oid = rc.relnamespace
WHERE con.contype = 'f' AND n.nspname = ANY($1)`

func loadFKs(ctx context.Context, q Querier, schemas []string, c *Catalog) error {
	rows, err := q.Query(ctx, fkSQL, schemas)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var fk FK
		if err := rows.Scan(&fk.Name, &fk.Table.Schema, &fk.Table.Name, &fk.Columns,
			&fk.RefTable.Schema, &fk.RefTable.Name, &fk.RefColumns, &fk.Deferrable); err != nil {
			return err
		}
		c.FKs = append(c.FKs, fk)
	}
	if err := rows.Err(); err != nil {
		return err
	}
	sort.Slice(c.FKs, func(i, j int) bool { return c.FKs[i].Name < c.FKs[j].Name })
	return nil
}

// Sequences owned by a column. After loading rows with explicit ids these are
// stale, and the application's next insert collides on the primary key, so the
// loader has to reset every one of them.
const sequenceSQL = `
SELECT sn.nspname::text, s.relname::text, tn.nspname::text, t.relname::text, a.attname::text
FROM pg_class s
JOIN pg_namespace sn ON sn.oid = s.relnamespace
JOIN pg_depend d ON d.objid = s.oid
 AND d.classid = 'pg_class'::regclass AND d.refclassid = 'pg_class'::regclass
JOIN pg_class t ON t.oid = d.refobjid
JOIN pg_namespace tn ON tn.oid = t.relnamespace
JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
WHERE s.relkind = 'S' AND d.deptype IN ('a', 'i') AND tn.nspname = ANY($1)`

func loadSequences(ctx context.Context, q Querier, schemas []string, c *Catalog) error {
	rows, err := q.Query(ctx, sequenceSQL, schemas)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var s Sequence
		if err := rows.Scan(&s.Ref.Schema, &s.Ref.Name, &s.Table.Schema, &s.Table.Name,
			&s.Column); err != nil {
			return err
		}
		if t, ok := c.Tables[s.Table.String()]; ok {
			t.Sequences = append(t.Sequences, s)
		}
	}
	return rows.Err()
}

func sameCols(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func containsCols(sets [][]string, cols []string) bool {
	for _, s := range sets {
		if sameCols(s, cols) {
			return true
		}
	}
	return false
}
